# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
      kernelModules = [];
    };
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems."/" = {
    device = "/dev/mapper/luks-b529a7f0-3ad7-498e-a326-1ba125bba663";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-b529a7f0-3ad7-498e-a326-1ba125bba663".device = "/dev/disk/by-uuid/b529a7f0-3ad7-498e-a326-1ba125bba663";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/42E6-E23E";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
